### ISSUE TITLE
será que vale a pena utilizar arquitetura de Comandos?

### ISSUE THREAD

**Issue by yuriserka** [yuriserka/lpzin#15]
Fazer no estilo TP1, acho que ficaria interessante e melhoraria a comunicação entre os módulos assim como ficaria mais coeso e menos acoplado.

ref.: https://en.wikipedia.org/wiki/Command_pattern

**Comment by henrique-mariano** [comment]
Vou mudar a estrutura dos controllers, agora cada controller terá sua struct onde terá seus métodos associados, com isso os módulos serão mais coesos e definidos.
